import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from fpdf import FPDF
import base64

# --- PAGE CONFIG ---
###st.set_page_config(page_title="2025 Omni-Tax Strategist", layout="wide", initial_sidebar_state="expanded")
# --- SEO & PAGE CONFIG ---
st.set_page_config(
    page_title="US Tax Planner",
    page_icon="📉",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'About': "# US Tax Strategist\nCalculates Federal, State, and Capital Gains taxes."
    }
)

# --- CSS STYLING ---
st.markdown("""
    <style>
    .main { background-color: #f4f6f9; }
    .stMetric { background-color: white; padding: 15px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    </style>
    """, unsafe_allow_html=True)

# --- CONSTANTS: FEDERAL (2025) ---
FED_BRACKETS = {
    'Single': [
        (11925, 0.10), (48475, 0.12), (103350, 0.22), 
        (197300, 0.24), (250525, 0.32), (626350, 0.35), (float('inf'), 0.37)
    ],
    'Married Joint': [
        (23850, 0.10), (96950, 0.12), (206700, 0.22), 
        (394600, 0.24), (501050, 0.32), (751600, 0.35), (float('inf'), 0.37)
    ],
    # ADDED: Head of Household (Wider brackets than Single)
    'Head of Household': [
        (17000, 0.10), (64850, 0.12), (103350, 0.22), 
        (197300, 0.24), (250500, 0.32), (626350, 0.35), (float('inf'), 0.37)
    ]
}

LTCG_BRACKETS = {
    'Single': [(48350, 0.0), (533400, 0.15), (float('inf'), 0.20)],
    'Married Joint': [(96700, 0.0), (600050, 0.15), (float('inf'), 0.20)],
    # ADDED: Head of Household (0% up to ~64k, 15% up to ~566k)
    'Head of Household': [(64750, 0.0), (566700, 0.15), (float('inf'), 0.20)]
}

STD_DEDUCTION = {
    'Single': 15000, 
    'Married Joint': 30000,
    'Head of Household': 22500 # Higher standard deduction
}

SENIOR_BOOST = {
    'Single': 1950, 
    'Married Joint': 1550,
    'Head of Household': 1950 
} 

NIIT_THRESH = {
    'Single': 200000, 
    'Married Joint': 250000,
    'Head of Household': 200000 # Same threshold as Single
}

SALT_CAP = 10000

# --- CONSTANTS: STATE ---
STATE_DATA = {
    "Texas (0%)": {"type": "none"},
    "Florida (0%)": {"type": "none"},
    "Washington (0%*)": {"type": "none"},
    "California (High)": {
        "type": "progressive",
        "brackets_single": [(11459, 0.01), (27169, 0.02), (42879, 0.04), (59528, 0.06), (75225, 0.08), (384534, 0.093), (461426, 0.103), (769062, 0.113), (1000000, 0.123), (float('inf'), 0.144)],
        "brackets_joint": [(22918, 0.01), (54338, 0.02), (85758, 0.04), (119056, 0.06), (150450, 0.08), (769068, 0.093), (922852, 0.103), (1538124, 0.113), (2000000, 0.123), (float('inf'), 0.144)]
    },
    "New York (High)": {
        "type": "progressive",
        "brackets_single": [(8500, 0.04), (11700, 0.045), (13900, 0.0525), (80650, 0.055), (215400, 0.06), (1077550, 0.0685), (5000000, 0.0965), (25000000, 0.103), (float('inf'), 0.109)],
        "brackets_joint": [(17150, 0.04), (23600, 0.045), (27900, 0.0525), (161550, 0.055), (323200, 0.06), (2155350, 0.0685), (5000000, 0.0965), (float('inf'), 0.109)]
    },
    "Custom / Other": {"type": "flat_input"}
}

# --- LOGIC ENGINES ---
def get_ledger_dataframe(results, w2_in):
    """
    Creates the Dataframe for the Ledger. 
    We separate this logic so we can use it for both the UI and the PDF.
    """
    data = {
        "Category": [
            "W2 Income", 
            "Net Short-Term Gains", 
            "Net Long-Term Gains", 
            "---", 
            "Federal Ordinary Tax", 
            "Federal LTCG Tax", 
            "NIIT Surtax (3.8%)", 
            "Medicare Surtax (0.9%)", 
            "State Tax", 
            "---", 
            "TOTAL LIABILITY"
        ],
        "Amount": [
            w2_in, 
            results['Breakdown'][0],  # Net ST
            results['Breakdown'][1],  # Net LT
            0, # Spacer value
            results['Federal Ordinary'], 
            results['Federal LTCG'], 
            results['NIIT'], 
            results['Medicare'], 
            results['State Tax'], 
            0, # Spacer value
            results['Total Tax']
        ]
    }
    return pd.DataFrame(data)

def create_advanced_pdf(results, state_pick, detailed_df, inputs):
    pdf = FPDF()
    pdf.add_page()
    
    # --- HEADER ---
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, "Strategic Tax Report", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Generated by Omni-Tax Strategist", ln=True, align='C')
    pdf.ln(10)
    
    # --- SECTION 1: EXECUTIVE SUMMARY ---
    pdf.set_fill_color(240, 240, 240) # Light Gray background
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Executive Summary", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    # Profile Data
    pdf.cell(95, 8, f"Filing Status: {inputs['status']}", ln=0)
    pdf.cell(95, 8, f"State: {state_pick}", ln=1)
    pdf.cell(95, 8, f"Total Income (MAGI): ${results['MAGI']:,.0f}", ln=0)
    pdf.cell(95, 8, f"Age: {inputs['age']}", ln=1)
    
    # Results Data
    pdf.ln(4)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(50, 8, "Total Tax Liability:", ln=0)
    pdf.set_font("Arial", size=11)
    pdf.cell(50, 8, f"${results['Total Tax']:,.2f}", ln=1)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(50, 8, "Effective Tax Rate:", ln=0)
    pdf.set_font("Arial", size=11)
    pdf.cell(50, 8, f"{(results['Total Tax']/results['MAGI']):.1%}", ln=1)
    
    # Surtax Warnings
    if results['NIIT'] > 0:
        pdf.set_text_color(194, 24, 7) # Red
        pdf.cell(0, 8, f"(!) NIIT Surtax Triggered: ${results['NIIT']:,.2f}", ln=1)
        pdf.set_text_color(0, 0, 0) # Reset color
    
    pdf.ln(5)

    # --- SECTION 2: FEDERAL VS STATE SPLIT (Tab 2 Data) ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Jurisdiction Breakdown", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    fed_share = (results['Total Tax'] - results['State Tax']) / results['Total Tax'] if results['Total Tax'] > 0 else 0
    state_share = results['State Tax'] / results['Total Tax'] if results['Total Tax'] > 0 else 0
    
    pdf.cell(0, 8, f"Federal Tax: ${results['Total Tax'] - results['State Tax']:,.2f} ({fed_share:.1%})", ln=1)
    pdf.cell(0, 8, f"State Tax:   ${results['State Tax']:,.2f} ({state_share:.1%})", ln=1)
    
    if results['State Tax'] > 10000:
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 8, "Note: You hit the $10,000 SALT Cap limit on federal deductions.", ln=1)
    
    pdf.ln(5)

    # --- SECTION 3: DETAILED LEDGER (Tab 3 Data) ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. Detailed Tax Ledger", ln=True, fill=True)
    pdf.ln(4)
    
    # Table Header
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(120, 8, "Category", border=1)
    pdf.cell(60, 8, "Amount", border=1, ln=1, align='R')
    
    # Table Rows
    pdf.set_font("Arial", size=10)
    for index, row in detailed_df.iterrows():
        category = str(row['Category'])
        amount = row['Amount']
        
        # Skip spacer rows
        if "---" in category:
            continue
            
        # Format Amount
        if amount == 0:
            fmt_amt = "-"
        elif amount < 0: # Deductions
            fmt_amt = f"-${abs(amount):,.2f}"
        else:
            fmt_amt = f"${amount:,.2f}"
            
        # Draw Row
        pdf.cell(120, 8, category, border=1)
        pdf.cell(60, 8, fmt_amt, border=1, ln=1, align='R')

    return pdf.output(dest="S").encode("latin-1")

def calculate_state_tax(taxable_income_federal, status, state_selection, custom_rate=0):
    if state_selection not in STATE_DATA: return 0
    state_info = STATE_DATA[state_selection]
    
    if state_info["type"] == "none": return 0
    elif state_info["type"] == "flat_input": return taxable_income_federal * (custom_rate / 100.0)
    elif state_info["type"] == "progressive":
        brackets = state_info["brackets_joint"] if status == 'Married Joint' else state_info["brackets_single"]
        tax = 0
        prev = 0
        for limit, rate in brackets:
            if taxable_income_federal > prev:
                amt = min(taxable_income_federal, limit) - prev
                tax += amt * rate
                prev = limit
            else: break
        return tax
    return 0

def net_schedule_d(st_stock, lt_stock, futures_1256):
    f_lt = futures_1256 * 0.60
    f_st = futures_1256 * 0.40
    
    tot_st = st_stock + f_st
    tot_lt = lt_stock + f_lt
    
    final_st, final_lt, deduct = 0, 0, 0
    
    if tot_st >= 0 and tot_lt >= 0:
        final_st, final_lt = tot_st, tot_lt
    elif tot_st < 0 and tot_lt < 0:
        deduct = min(3000, abs(tot_st + tot_lt))
    elif tot_st < 0 < tot_lt:
        net = tot_lt + tot_st
        if net >= 0: final_lt = net
        else: deduct = min(3000, abs(net))
    elif tot_lt < 0 < tot_st:
        net = tot_st + tot_lt
        if net >= 0: final_st = net
        else: deduct = min(3000, abs(net))
        
    return final_st, final_lt, deduct, (f_st, f_lt)

def calculate_full_liability(w2, st_gains, lt_gains, futures, status, state_name, custom_state_rate, deductions_manual, age):
    # 1. Netting
    net_st, net_lt, cap_loss_deduct, split_1256 = net_schedule_d(st_gains, lt_gains, futures)
    total_ord_income = w2 + net_st
    
    # 2. Deductions
    base_std_ded = STD_DEDUCTION[status]
    if age >= 65: base_std_ded += SENIOR_BOOST[status]
    
    est_fed_agi = total_ord_income + net_lt - cap_loss_deduct
    est_state_tax = calculate_state_tax(est_fed_agi, status, state_name, custom_state_rate)
    salt_deduction = min(SALT_CAP, est_state_tax)
    total_itemized = deductions_manual + salt_deduction
    final_deduction = max(base_std_ded, total_itemized)
    
    # 3. Federal Taxable Income
    fed_taxable_ord = max(0, total_ord_income - cap_loss_deduct - final_deduction)
    
    # 4. Federal Calculation
    fed_ord_tax = 0
    prev = 0
    marginal_rate = 0.0 # Capture this for Wealth Projection
    
    for lim, rate in FED_BRACKETS[status]:
        if fed_taxable_ord > prev:
            amt = min(fed_taxable_ord, lim) - prev
            fed_ord_tax += amt * rate
            prev = lim
            if fed_taxable_ord > 0: marginal_rate = rate
        else: break
            
    fed_ltcg_tax = 0
    curr_stack = fed_taxable_ord
    rem_lt = net_lt
    for lim, rate in LTCG_BRACKETS[status]:
        if curr_stack < lim:
            space = lim - curr_stack
            amt = min(rem_lt, space)
            fed_ltcg_tax += amt * rate
            curr_stack += amt
            rem_lt -= amt
            
    magi = w2 + net_st + net_lt + futures - cap_loss_deduct
    niit = min(net_st + net_lt, max(0, magi - NIIT_THRESH[status])) * 0.038
    med = max(0, w2 - 200000) * 0.009
    
    # 5. State Calculation
    state_taxable = max(0, (total_ord_income + net_lt - cap_loss_deduct) - final_deduction)
    final_state_tax = calculate_state_tax(state_taxable, status, state_name, custom_state_rate)
    
    return {
        "Federal Ordinary": fed_ord_tax,
        "Federal LTCG": fed_ltcg_tax,
        "NIIT": niit,
        "Medicare": med,
        "State Tax": final_state_tax,
        "Total Tax": fed_ord_tax + fed_ltcg_tax + niit + med + final_state_tax,
        "Breakdown": (net_st, net_lt, cap_loss_deduct),
        "Deduction Used": final_deduction,
        "Std Deduction Limit": base_std_ded,
        "MAGI": magi,
        "Marginal Rate": marginal_rate
    }

# --- SIDEBAR INPUTS ---
with st.sidebar:
    st.header("1. Profile & Location")
    status = st.selectbox("Filing Status", ["Single", "Married Joint","Head of Household"], key="sidebar_filing")
    age = st.number_input("Current Age", min_value=18, max_value=100, value=45)
    state_pick = st.selectbox("State of Residence", list(STATE_DATA.keys()), index=3)
    
    custom_state_rate = 0.0
    if state_pick == "Custom / Other":
        custom_state_rate = st.number_input("Est. State Tax Rate (%)", 0.0, 15.0, 5.0)

    st.header("2. Income Sources")
    w2_in = st.number_input("W2 / Business Income", value=80000, step=5000)
    st_in = st.number_input("Short-Term Gain/Loss", value=0)
    lt_in = st.number_input("Long-Term Gain/Loss", value=12000)
    fut_in = st.number_input("Futures (Sec 1256)", value=0)
    
    st.header("3. Strategies")
    strat_charity = st.number_input("Charitable Giving ($)", value=0)
    
    max_401k_limit = 23500
    if age >= 50:
        max_401k_limit = 31000 
        st.info("✅ Catch-Up Eligible (50+)")

    strat_401k = st.checkbox(f"Max 401k (${max_401k_limit:,} deduction)", value=False)
    manual_deduct = strat_charity + (max_401k_limit if strat_401k else 0)

    # TIP JAR
    st.divider()
    st.markdown("### ☕ Support the Dev")
    st.caption("Did this tool help you save money?")
    st.markdown(
        """
        <a href="https://www.buymeacoffee.com/YOUR_USERNAME" target="_blank">
            <img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 40px !important;width: 150px !important;" >
        </a>
        """,
        unsafe_allow_html=True
    )

# --- MAIN CALCULATION ---

# THIS WAS THE LINE CAUSING THE ERROR. NOW IT MATCHES THE DEFINITION EXACTLY (9 ARGUMENTS).
results = calculate_full_liability(w2_in, st_in, lt_in, fut_in, status, state_pick, custom_state_rate, manual_deduct, age)

# --- GENERATE DATAFRAME (GLOBAL) ---
# We create the DF here so it is available for both Tab 3 AND the PDF Report
ledger_df = get_ledger_dataframe(results, w2_in)

# --- PDF GENERATION (SIDEBAR) ---
# Now 'ledger_df' is available to pass into the PDF function
input_summary = {"status": status, "age": age}
pdf_data = create_advanced_pdf(results, state_pick, ledger_df, input_summary)

st.sidebar.divider()
st.sidebar.download_button(
    label="📄 Download Full Report (PDF)",
    data=pdf_data,
    file_name="Tax_Strategy_Report.pdf",
    mime="application/pdf"
)

# --- DASHBOARD ---

st.title("🇺🇸 Omni-Tax Strategist")
st.markdown(f"### *Consolidated Federal + {state_pick} Tax Analysis*")

# Top Level Cards
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Tax Bill", f"${results['Total Tax']:,.0f}")
eff_rate = results['Total Tax'] / results['MAGI'] if results['MAGI'] > 0 else 0
col2.metric("True Effective Rate", f"{eff_rate:.1%}")
col3.metric("Marginal Bracket", f"{results['Marginal Rate']:.0%}")
col4.metric("Deduction Used", f"${results['Deduction Used']:,.0f}")

# Visualizations
tab1, tab2, tab3, tab4 = st.tabs(["📊 Liability Waterfall", "🌍 Federal vs State Split", "🧾 Detailed Ledger", "🔮 Wealth Projection"])

with tab1:
    fig = go.Figure(go.Waterfall(
        name = "Tax Build", orientation = "v",
        measure = ["relative", "relative", "relative", "relative", "relative", "total"],
        x = ["Fed Ordinary", "Fed CapGains", "NIIT (3.8%)", "Medicare (0.9%)", "State Tax", "TOTAL"],
        textposition = "outside",
        text = [f"${x/1000:.1f}k" for x in [results['Federal Ordinary'], results['Federal LTCG'], results['NIIT'], results['Medicare'], results['State Tax'], results['Total Tax']]],
        y = [results['Federal Ordinary'], results['Federal LTCG'], results['NIIT'], results['Medicare'], results['State Tax'], results['Total Tax']],
        connector = {"line":{"color":"rgb(63, 63, 63)"}},
    ))
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    labels = ['Federal Tax', 'State Tax']
    values = [results['Total Tax'] - results['State Tax'], results['State Tax']]
    c1, c2 = st.columns([1, 2])
    with c1:
        st.markdown("### The State Burden")
        share = results['State Tax'] / results['Total Tax'] if results['Total Tax'] > 0 else 0
        st.write(f"In **{state_pick}**, State Tax accounts for **{share:.1%}** of your total liability.")
    with c2:
        fig2 = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.4)])
        st.plotly_chart(fig2, use_container_width=True)

with tab3:
    data = {
        "Category": ["W2 Income", "Net Short-Term", "Net Long-Term", "---", "Federal Ordinary Tax", "Federal LTCG Tax", "NIIT Surtax", "Medicare Surtax", "State Tax", "---", "TOTAL LIABILITY"],
        "Amount": [
            w2_in, results['Breakdown'][0], results['Breakdown'][1], 0, 
            results['Federal Ordinary'], results['Federal LTCG'], results['NIIT'], results['Medicare'], results['State Tax'], 0, results['Total Tax']
        ]
    }
    df = pd.DataFrame(data)
    st.dataframe(df.style.format({"Amount": lambda x: f"${x:,.2f}" if x > 0 else ("" if x == 0 else f"-${abs(x):,.2f}")}), use_container_width=True)

with tab4:
    st.subheader("🔮 Long-Term Wealth Projection")
    st.markdown("Compare investing **Pre-Tax** (Traditional) vs. **Post-Tax** (Roth) vs. **Brokerage**.")
    
    # --- 1. DEFINE INPUTS FIRST (So 'growth_rate' exists) ---
    col_p1, col_p2, col_p3 = st.columns(3)
    with col_p1:
        invest_budget = st.number_input("Annual Gross Budget ($)", value=25000, step=1000)
    with col_p2:
        # This is where 'growth_rate' is defined
        growth_rate = st.slider("Market Growth Rate (%)", 3.0, 12.0, 7.0) / 100.0
    with col_p3:
        years_to_grow = st.slider("Years to Grow", 5, 40, 65 - age if age < 65 else 10)

    st.divider()
    
    # --- 2. INFLATION LOGIC (Now it works because growth_rate exists) ---
    adjust_inflation = st.checkbox("Adjust for Inflation (Show Real Purchasing Power?)", value=True)
    
    # Logic: Nominal Rate vs Real Rate
    inflation_rate = 0.03 # Assumed 3%
    if adjust_inflation:
        # Fisher Equation for Real Interest Rate
        calc_rate = (1 + growth_rate) / (1 + inflation_rate) - 1
    else:
        calc_rate = growth_rate

    # --- 3. SIMULATION ---
    current_marg_rate = results['Marginal Rate']
    st.write("**Future Tax Scenario:** Do you expect your effective tax rate in retirement to be higher or lower than today?")
    future_tax_rate = st.slider("Est. Effective Tax Rate in Retirement (%)", 0, 50, 20) / 100.0
    
    trad_corpus = 0
    trad_values = []
    
    roth_contribution = invest_budget * (1 - current_marg_rate)
    roth_corpus = 0
    roth_values = []
    
    brok_corpus = 0
    brok_values = []
    
    years_axis = list(range(years_to_grow + 1))
    
    for _ in years_axis:
        # Use 'calc_rate' (which handles the inflation logic) instead of 'growth_rate'
        
        # A. Traditional (Pre-Tax)
        # Apply growth, then tax is taken ONLY at withdrawal (simulated in the list append)
        trad_values.append(trad_corpus * (1 - future_tax_rate))
        trad_corpus = (trad_corpus + invest_budget) * (1 + calc_rate)
        
        # B. Roth (Post-Tax)
        # Tax paid upfront, grows tax-free
        roth_values.append(roth_corpus)
        roth_corpus = (roth_corpus + roth_contribution) * (1 + calc_rate)
        
        # C. Brokerage (Taxable)
        # Tax paid upfront. Growth is taxed at 15% LTCG.
        # Note: We apply tax drag annually or at end. For simplicity, we calculate net value.
        brok_gain = brok_corpus - (roth_contribution * _) if _ > 0 else 0
        brok_values.append(brok_corpus - (brok_gain * 0.15)) 
        brok_corpus = (brok_corpus + roth_contribution) * (1 + calc_rate)

    # --- 4. PLOT ---
    fig_proj = go.Figure()
    fig_proj.add_trace(go.Scatter(x=years_axis, y=trad_values, mode='lines', name=f'Traditional (if Future Tax={future_tax_rate:.0%})', line=dict(color='blue')))
    fig_proj.add_trace(go.Scatter(x=years_axis, y=roth_values, mode='lines', name=f'Roth (Taxed Now at {current_marg_rate:.0%})', line=dict(color='green', width=4)))
    fig_proj.add_trace(go.Scatter(x=years_axis, y=brok_values, mode='lines', name='Taxable Brokerage', line=dict(color='gray', dash='dot')))
    
    title_suffix = "(Inflation Adjusted)" if adjust_inflation else "(Nominal Dollars)"
    fig_proj.update_layout(title=f"Net After-Tax Purchasing Power {title_suffix}", xaxis_title="Years", yaxis_title="Net Value ($)")
    st.plotly_chart(fig_proj, use_container_width=True)
    
    # Analysis
    final_trad = trad_values[-1]
    final_roth = roth_values[-1]
    diff = final_trad - final_roth
    
    if diff > 1000:
        st.success(f"✅ **Traditional Wins:** If your future tax rate is lower ({future_tax_rate:.0%}), Pre-Tax investing generates **${diff:,.0f}** more wealth.")
    elif diff < -1000:
        st.success(f"✅ **Roth Wins:** If your future tax rate is higher (or similar), locking in today's rate generates **${abs(diff):,.0f}** more wealth.")
    else:
        st.warning("⚖️ **It's a Tie:** The tax rates are similar enough that it doesn't strictly matter.")



