import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from fpdf import FPDF
import base64

# --- SEO & PAGE CONFIG ---
st.set_page_config(
    page_title="US Tax Planner & TLH Calculator",
    page_icon="📉",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'About': "# US Tax Strategist\nCalculates Federal, State, and Capital Gains taxes."
    }
)

# --- INJECT SEO HEADER (Hidden) ---
st.markdown("""
    <h1 style='position: absolute; top: -1000px; left: -1000px;'>
        Free US Income Tax Planner, Tax Loss Harvesting Calculator, Capital Gains Offset Tool, 
        and State Tax Calculator for California, New York, Texas, and Florida.
    </h1>
    <style>
    .main { background-color: #f4f6f9; }
    .stMetric { background-color: white; padding: 15px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    </style>
    """, unsafe_allow_html=True)

# --- CONSTANTS: FEDERAL (2025) ---
FED_BRACKETS = {
    'Single': [(11925, 0.10), (48475, 0.12), (103350, 0.22), (197300, 0.24), (250525, 0.32), (626350, 0.35), (float('inf'), 0.37)],
    'Married Joint': [(23850, 0.10), (96950, 0.12), (206700, 0.22), (394600, 0.24), (501050, 0.32), (751600, 0.35), (float('inf'), 0.37)]
}
LTCG_BRACKETS = {
    'Single': [(48350, 0.0), (533400, 0.15), (float('inf'), 0.20)],
    'Married Joint': [(96700, 0.0), (600050, 0.15), (float('inf'), 0.20)]
}
STD_DEDUCTION = {'Single': 15000, 'Married Joint': 30000}
SENIOR_BOOST = {'Single': 1950, 'Married Joint': 1550} 
NIIT_THRESH = {'Single': 200000, 'Married Joint': 250000}
SALT_CAP = 10000  

# --- CONSTANTS: STATE (Simplified 2025 Models) ---
STATE_DATA = {
    "Texas (0%)": {"type": "none"},
    "Florida (0%)": {"type": "none"},
    "Washington (0%*)": {"type": "none"},
    "California (High)": {
        "type": "progressive",
        "brackets_single": [(11459, 0.01), (27169, 0.02), (42879, 0.04), (59528, 0.06), (75225, 0.08), (384534, 0.093), (461426, 0.103), (769062, 0.113), (1000000, 0.123), (float('inf'), 0.144)],
        "brackets_joint": [(22918, 0.01), (54338, 0.02), (85758, 0.04), (119056, 0.06), (150450, 0.08), (769068, 0.093), (922852, 0.103), (1538124, 0.113), (2000000, 0.123), (float('inf'), 0.144)]
    },
    "New York (High)": {
        "type": "progressive",
        "brackets_single": [(8500, 0.04), (11700, 0.045), (13900, 0.0525), (80650, 0.055), (215400, 0.06), (1077550, 0.0685), (5000000, 0.0965), (25000000, 0.103), (float('inf'), 0.109)],
        "brackets_joint": [(17150, 0.04), (23600, 0.045), (27900, 0.0525), (161550, 0.055), (323200, 0.06), (2155350, 0.0685), (5000000, 0.0965), (float('inf'), 0.109)]
    },
    "Custom / Other": {"type": "flat_input"}
}

# --- LOGIC ENGINES ---

from fpdf import FPDF

def create_advanced_pdf(results, state_pick, detailed_df, inputs):
    pdf = FPDF()
    pdf.add_page()
    
    # --- HEADER ---
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, "Strategic Tax Report", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Generated by Omni-Tax Strategist", ln=True, align='C')
    pdf.ln(10)
    
    # --- SECTION 1: EXECUTIVE SUMMARY ---
    pdf.set_fill_color(240, 240, 240) # Light Gray background
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Executive Summary", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    # Profile Data
    pdf.cell(95, 8, f"Filing Status: {inputs['status']}", ln=0)
    pdf.cell(95, 8, f"State: {state_pick}", ln=1)
    pdf.cell(95, 8, f"Total Income (MAGI): ${results['MAGI']:,.0f}", ln=0)
    pdf.cell(95, 8, f"Age: {inputs['age']}", ln=1)
    
    # Results Data
    pdf.ln(4)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(50, 8, "Total Tax Liability:", ln=0)
    pdf.set_font("Arial", size=11)
    pdf.cell(50, 8, f"${results['Total Tax']:,.2f}", ln=1)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(50, 8, "Effective Tax Rate:", ln=0)
    pdf.set_font("Arial", size=11)
    pdf.cell(50, 8, f"{(results['Total Tax']/results['MAGI']):.1%}", ln=1)
    
    # Surtax Warnings
    if results['NIIT'] > 0:
        pdf.set_text_color(194, 24, 7) # Red
        pdf.cell(0, 8, f"(!) NIIT Surtax Triggered: ${results['NIIT']:,.2f}", ln=1)
        pdf.set_text_color(0, 0, 0) # Reset color
    
    pdf.ln(5)

    # --- SECTION 2: FEDERAL VS STATE SPLIT (Tab 2 Data) ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Jurisdiction Breakdown", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    fed_share = (results['Total Tax'] - results['State Tax']) / results['Total Tax'] if results['Total Tax'] > 0 else 0
    state_share = results['State Tax'] / results['Total Tax'] if results['Total Tax'] > 0 else 0
    
    pdf.cell(0, 8, f"Federal Tax: ${results['Total Tax'] - results['State Tax']:,.2f} ({fed_share:.1%})", ln=1)
    pdf.cell(0, 8, f"State Tax:   ${results['State Tax']:,.2f} ({state_share:.1%})", ln=1)
    
    if results['State Tax'] > 10000:
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 8, "Note: You hit the $10,000 SALT Cap limit on federal deductions.", ln=1)
    
    pdf.ln(5)

    # --- SECTION 3: DETAILED LEDGER (Tab 3 Data) ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. Detailed Tax Ledger", ln=True, fill=True)
    pdf.ln(4)
    
    # Table Header
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(120, 8, "Category", border=1)
    pdf.cell(60, 8, "Amount", border=1, ln=1, align='R')
    
    # Table Rows
    pdf.set_font("Arial", size=10)
    for index, row in detailed_df.iterrows():
        category = str(row['Category'])
        amount = row['Amount']
        
        # Skip spacer rows
        if "---" in category:
            continue
            
        # Format Amount
        if amount == 0:
            fmt_amt = "-"
        elif amount < 0: # Deductions
            fmt_amt = f"-${abs(amount):,.2f}"
        else:
            fmt_amt = f"${amount:,.2f}"
            
        # Draw Row
        pdf.cell(120, 8, category, border=1)
        pdf.cell(60, 8, fmt_amt, border=1, ln=1, align='R')

    return pdf.output(dest="S").encode("latin-1")

def calculate_state_tax(taxable_income_federal, status, state_selection, custom_rate=0):
    if state_selection not in STATE_DATA: return 0
    state_info = STATE_DATA[state_selection]
    
    if state_info["type"] == "none": return 0
    elif state_info["type"] == "flat_input": return taxable_income_federal * (custom_rate / 100.0)
    elif state_info["type"] == "progressive":
        brackets = state_info["brackets_joint"] if status == 'Married Joint' else state_info["brackets_single"]
        tax = 0
        prev = 0
        for limit, rate in brackets:
            if taxable_income_federal > prev:
                amt = min(taxable_income_federal, limit) - prev
                tax += amt * rate
                prev = limit
            else: break
        return tax
    return 0

def net_schedule_d(st_stock, lt_stock, futures_1256):
    """
    Trader Logic + TLH Logic:
    1. Split Futures 60/40.
    2. Add ST Stock + ST Futures.
    3. Add LT Stock + LT Futures.
    4. Perform Netting (Losses offset Gains).
    """
    f_lt = futures_1256 * 0.60
    f_st = futures_1256 * 0.40
    
    tot_st = st_stock + f_st
    tot_lt = lt_stock + f_lt
    
    final_st, final_lt, deduct, carryover = 0, 0, 0, 0
    
    # CASE 1: Both Positive
    if tot_st >= 0 and tot_lt >= 0:
        final_st, final_lt = tot_st, tot_lt
        
    # CASE 2: Both Negative
    elif tot_st < 0 and tot_lt < 0:
        total_loss = abs(tot_st + tot_lt)
        deduct = min(3000, total_loss)
        carryover = total_loss - deduct
        
    # CASE 3: Mixed (Netting required)
    elif tot_st < 0 < tot_lt: # ST Loss, LT Gain
        net = tot_lt + tot_st
        if net >= 0: 
            final_lt = net
        else: 
            deduct = min(3000, abs(net))
            carryover = abs(net) - deduct
            
    elif tot_lt < 0 < tot_st: # LT Loss, ST Gain
        net = tot_st + tot_lt
        if net >= 0: 
            final_st = net
        else: 
            deduct = min(3000, abs(net))
            carryover = abs(net) - deduct
        
    return final_st, final_lt, deduct, carryover

def calculate_full_liability(w2, st_gains, lt_gains, futures, tlh_amount, status, state_name, custom_state_rate, deductions_manual, age):
    
    # 1. APPLY TLH STRATEGY
    # We treat Harvested Losses as a negative Short-Term number. 
    # This is standard planning (ST losses are more valuable, so we assume best case or general pool).
    adjusted_st_gains = st_gains - tlh_amount
    
    # 2. Netting Schedule D
    net_st, net_lt, cap_loss_deduct, carryover = net_schedule_d(adjusted_st_gains, lt_gains, futures)
    
    total_ord_income = w2 + net_st
    
    # 3. Deductions (Age Aware)
    base_std_ded = STD_DEDUCTION[status]
    if age >= 65:
        base_std_ded += SENIOR_BOOST[status]

    # Calculate State Tax to check SALT Cap
    est_fed_agi = total_ord_income + net_lt - cap_loss_deduct
    est_state_tax = calculate_state_tax(est_fed_agi, status, state_name, custom_state_rate)
    
    salt_deduction = min(SALT_CAP, est_state_tax)
    total_itemized = deductions_manual + salt_deduction
    
    final_deduction = max(base_std_ded, total_itemized)
    
    # 4. Federal Taxable Income
    fed_taxable_ord = max(0, total_ord_income - cap_loss_deduct - final_deduction)
    
    # 5. Federal Calculation
    fed_ord_tax = 0
    prev = 0
    for lim, rate in FED_BRACKETS[status]:
        if fed_taxable_ord > prev:
            amt = min(fed_taxable_ord, lim) - prev
            fed_ord_tax += amt * rate
            prev = lim
        else: break
            
    fed_ltcg_tax = 0
    curr_stack = fed_taxable_ord
    rem_lt = net_lt
    for lim, rate in LTCG_BRACKETS[status]:
        if curr_stack < lim:
            space = lim - curr_stack
            amt = min(rem_lt, space)
            fed_ltcg_tax += amt * rate
            curr_stack += amt
            rem_lt -= amt
            
    magi = w2 + net_st + net_lt + futures - cap_loss_deduct # Simplified MAGI
    niit = min(net_st + net_lt, max(0, magi - NIIT_THRESH[status])) * 0.038
    med = max(0, w2 - 200000) * 0.009
    
    fed_total = fed_ord_tax + fed_ltcg_tax + niit + med
    
    # 6. State Calculation
    state_taxable = max(0, (total_ord_income + net_lt - cap_loss_deduct) - final_deduction)
    final_state_tax = calculate_state_tax(state_taxable, status, state_name, custom_state_rate)
    
    return {
        "Federal Ordinary": fed_ord_tax,
        "Federal LTCG": fed_ltcg_tax,
        "NIIT": niit,
        "Medicare": med,
        "State Tax": final_state_tax,
        "Total Tax": fed_total + final_state_tax,
        "Breakdown": (net_st, net_lt, cap_loss_deduct),
        "Carryover": carryover,
        "Deduction Used": final_deduction,
        "Std Deduction Limit": base_std_ded,
        "MAGI": magi
    }

def get_ledger_dataframe(results, w2_in):
    """
    Creates the Dataframe for the Ledger. 
    We separate this logic so we can use it for both the UI and the PDF.
    """
    data = {
        "Category": [
            "W2 Income", 
            "Net Short-Term Gains", 
            "Net Long-Term Gains", 
            "---", 
            "Federal Ordinary Tax", 
            "Federal LTCG Tax", 
            "NIIT Surtax (3.8%)", 
            "Medicare Surtax (0.9%)", 
            "State Tax", 
            "---", 
            "TOTAL LIABILITY"
        ],
        "Amount": [
            w2_in, 
            results['Breakdown'][0],  # Net ST
            results['Breakdown'][1],  # Net LT
            0, # Spacer value
            results['Federal Ordinary'], 
            results['Federal LTCG'], 
            results['NIIT'], 
            results['Medicare'], 
            results['State Tax'], 
            0, # Spacer value
            results['Total Tax']
        ]
    }
    return pd.DataFrame(data)

# --- SIDEBAR INPUTS ---
with st.sidebar:
    st.header("1. Profile & Location")
    status = st.selectbox("Filing Status", ["Single", "Married Joint"], key="sb_status")
    age = st.number_input("Current Age", min_value=18, max_value=100, value=45, key="sb_age")
    state_pick = st.selectbox("State of Residence", list(STATE_DATA.keys()), index=3, key="sb_state")
    
    custom_state_rate = 0.0
    if state_pick == "Custom / Other":
        custom_state_rate = st.number_input("Est. State Tax Rate (%)", 0.0, 15.0, 5.0, key="sb_custom_rate")

    st.header("2. Income Sources")
    w2_in = st.number_input("W2 / Business Income", value=180000, step=5000, key="sb_w2")
    st.caption("Investment Income (Consolidated 1099)")
    st_in = st.number_input("Short-Term Gain/Loss", value=5000, key="sb_st")
    lt_in = st.number_input("Long-Term Gain/Loss", value=15000, key="sb_lt")
    fut_in = st.number_input("Futures (Sec 1256)", value=0, key="sb_fut")
    
    st.header("3. Strategies")
    
    # Tax Loss Harvesting Input
    st.markdown("##### 📉 Tax-Loss Harvesting")
    enable_tlh = st.checkbox("Apply Harvested Losses?", key="sb_tlh_check")
    tlh_val = 0
    if enable_tlh:
        tlh_val = st.number_input("Total Harvested Loss ($)", min_value=0, value=3000, step=1000, key="sb_tlh_val", help="Enter the amount of losses you harvested. The calculator subtracts this from Short Term gains first.")

    st.markdown("##### ❤️ Deductions")
    strat_charity = st.number_input("Charitable Giving ($)", value=0, key="sb_charity")
    
    max_401k_limit = 23500
    if age >= 50:
        max_401k_limit = 31000 
        st.info("✅ Catch-Up Contribution Eligible (50+)")

    strat_401k = st.checkbox(f"Max 401k (${max_401k_limit:,} deduction)", value=False, key="sb_401k")
    
    manual_deduct = strat_charity + (max_401k_limit if strat_401k else 0)

    # --- TIP JAR ---
    st.divider() 
    st.markdown("### ☕ Support the Dev")
    st.write("Did this tool help you? Support keeps it free!")
    
    bmc_link = "https://www.buymeacoffee.com" 
    st.markdown(
        f"""
        <a href="{bmc_link}" target="_blank">
            <img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 40px !important;width: 150px !important;" >
        </a>
        """,
        unsafe_allow_html=True
    )

# --- MAIN PAGE DASHBOARD ---

st.title("🇺🇸 Omni-Tax Strategist")
st.markdown(f"### *Consolidated Federal + {state_pick} Tax Analysis*")

# --- CALCULATE ---
results = calculate_full_liability(w2_in, st_in, lt_in, fut_in, tlh_val, status, state_pick, custom_state_rate, manual_deduct, age)

# --- GENERATE DATAFRAME (GLOBAL) ---
# We create the DF here so it is available for both Tab 3 AND the PDF Report
ledger_df = get_ledger_dataframe(results, w2_in)

# --- PDF GENERATION (SIDEBAR) ---
# Now 'ledger_df' is available to pass into the PDF function
input_summary = {"status": status, "age": age}
pdf_data = create_advanced_pdf(results, state_pick, ledger_df, input_summary)

st.sidebar.divider()
st.sidebar.download_button(
    label="📄 Download Full Report (PDF)",
    data=pdf_data,
    file_name="Tax_Strategy_Report.pdf",
    mime="application/pdf"
)

# 1. Top Level Cards
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Tax Bill", f"${results['Total Tax']:,.0f}")
eff_rate = results['Total Tax'] / results['MAGI'] if results['MAGI'] > 0 else 0
col2.metric("True Effective Rate", f"{eff_rate:.1%}")
col3.metric("State Tax Portion", f"${results['State Tax']:,.0f}")
col4.metric("Deduction Used", f"${results['Deduction Used']:,.0f}", help=f"Higher of Itemized or Standard")

# 2. Logic Indicators
st.divider()

if results['Carryover'] > 0:
    st.success(f"📉 **Harvesting Success:** You have used the max $3,000 deduction against W2 income. You have **${results['Carryover']:,.0f}** in losses carrying over to next year.")
elif enable_tlh:
    st.success(f"✅ **Tax Loss Applied:** Your harvested losses fully offset your capital gains.")

if results['Deduction Used'] == results['Std Deduction Limit'] and age >= 65:
    st.success(f"👴 **Senior Benefit:** Standard Deduction increased to **${results['Std Deduction Limit']:,}**.")

if results['NIIT'] > 0:
    st.warning(f"⚠️ **NIIT Triggered:** +${results['NIIT']:,.0f} (3.8% Surtax).")

# 3. Visualizations
tab1, tab2, tab3 = st.tabs(["📊 Liability Waterfall", "🌍 Federal vs State Split", "🧾 Detailed Ledger"])

with tab1:
    fig = go.Figure(go.Waterfall(
        name = "Tax Build", orientation = "v",
        measure = ["relative", "relative", "relative", "relative", "relative", "total"],
        x = ["Fed Ordinary", "Fed CapGains", "NIIT (3.8%)", "Medicare (0.9%)", "State Tax", "TOTAL"],
        textposition = "outside",
        text = [f"${x/1000:.1f}k" for x in [results['Federal Ordinary'], results['Federal LTCG'], results['NIIT'], results['Medicare'], results['State Tax'], results['Total Tax']]],
        y = [results['Federal Ordinary'], results['Federal LTCG'], results['NIIT'], results['Medicare'], results['State Tax'], results['Total Tax']],
        connector = {"line":{"color":"rgb(63, 63, 63)"}},
    ))
    fig.update_layout(title="Sources of Tax Liability", height=450)
    st.plotly_chart(fig, use_container_width=True)
    pass

with tab2:
    labels = ['Federal Tax', 'State Tax']
    values = [results['Total Tax'] - results['State Tax'], results['State Tax']]
    
    c1, c2 = st.columns([1, 2])
    with c1:
        st.markdown("### The State Burden")
        share = results['State Tax'] / results['Total Tax'] if results['Total Tax'] > 0 else 0
        st.write(f"In **{state_pick}**, State Tax accounts for **{share:.1%}** of your total liability.")
        
        if results['State Tax'] > 10000:
            st.info("ℹ️ **SALT Cap Hit:** You paid >$10k in State Tax, but Federal deduction is capped at $10k.")
    with c2:
        fig2 = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.4)])
        st.plotly_chart(fig2, use_container_width=True)
        pass

with tab3:
    # NOW WE JUST DISPLAY THE GLOBAL DF
    # We use the custom lambda format for the UI display
    st.dataframe(
        ledger_df.style.format({
            "Amount": lambda x: f"${x:,.2f}" if x > 0 else ("" if x == 0 else f"-${abs(x):,.2f}")
        }), 
        use_container_width=True
    )


